sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t landshark42/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true landshark42/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-367069199586v'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
